"""
core/execution.py
-----------------
Deterministic execution metadata recorder.

Every call to :meth:`~dataintegrity.integrity.engine.IntegrityEngine.run`
automatically produces an :class:`ExecutionManifest` that captures *who*
ran *what* configuration against *which* data, making every audit fully
reproducible and traceable.
"""

from __future__ import annotations

import json
import platform
import sys
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, List, Optional

# ---------------------------------------------------------------------------
# Lazy version helpers — avoid hard import failures if a dep is not installed
# ---------------------------------------------------------------------------

def _safe_version(module_name: str) -> str:
    """Return a module's ``__version__`` or ``'unknown'`` if import fails."""
    try:
        import importlib
        mod = importlib.import_module(module_name)
        return getattr(mod, "__version__", "unknown")
    except Exception:
        return "unknown"


def _sdk_version() -> str:
    """Return the installed dataintegrity SDK version."""
    try:
        import importlib.metadata
        return importlib.metadata.version("dataintegrity")
    except Exception:
        try:
            from dataintegrity import __version__
            return __version__
        except Exception:
            return "unknown"


def _build_environment() -> Dict[str, str]:
    """
    Collect runtime environment metadata.

    Returns:
        Dict with keys: ``os``, ``os_release``, ``python_version``,
        ``pandas_version``, ``numpy_version``, ``scipy_version``.
    """
    return {
        "os": platform.system(),
        "os_release": platform.release(),
        "python_version": sys.version,
        "pandas_version": _safe_version("pandas"),
        "numpy_version": _safe_version("numpy"),
        "scipy_version": _safe_version("scipy"),
    }


# ---------------------------------------------------------------------------
# ExecutionManifest
# ---------------------------------------------------------------------------

@dataclass
class ExecutionManifest:
    """
    Captures deterministic metadata about a single integrity execution.

    An :class:`ExecutionManifest` is automatically generated by
    :meth:`~dataintegrity.integrity.engine.IntegrityEngine.run` and
    embedded inside the returned :class:`~dataintegrity.core.result_schema.DatasetAuditResult`.

    Attributes:
        run_id:                 UUID4 string uniquely identifying this audit run.
        timestamp:              UTC ISO-8601 timestamp of when the run started.
        dataset_fingerprint:    SHA-256 fingerprint of the dataset that was audited.
        config_hash:            SHA-256 hash of the :class:`IntegrityConfig` used.
        sdk_version:            ``dataintegrity`` package version string.
        python_version:         Full Python interpreter version string.
        environment:            Dict of runtime environment metadata (OS, lib versions).
        rules_executed:         Ordered list of rule IDs that were evaluated.
        drift_checks_executed:  Ordered list of drift check names that were evaluated.
        final_score:            The composite DataScore (0–100) produced by this run.
    """

    run_id: str
    timestamp: str
    dataset_fingerprint: str
    config_hash: str
    sdk_version: str
    python_version: str
    environment: Dict[str, str]
    rules_executed: List[str]
    drift_checks_executed: List[str]
    final_score: float

    # ------------------------------------------------------------------
    # Factory
    # ------------------------------------------------------------------

    @classmethod
    def create(
        cls,
        *,
        dataset_fingerprint: str,
        config_hash: str,
        rules_executed: List[str],
        final_score: float,
        drift_checks_executed: Optional[List[str]] = None,
    ) -> "ExecutionManifest":
        """
        Build a fully-populated :class:`ExecutionManifest` from minimal caller inputs.

        All environment metadata (OS, library versions, SDK version) is collected
        automatically at call time.

        Args:
            dataset_fingerprint: SHA-256 fingerprint of the audited dataset.
            config_hash:         SHA-256 hash of the config used for this run.
            rules_executed:      List of rule IDs that were evaluated.
            final_score:         Composite DataScore produced by this run (0–100).
            drift_checks_executed: Optional list of drift check names; defaults to ``[]``.

        Returns:
            A fully-populated :class:`ExecutionManifest` instance.

        Example::

            manifest = ExecutionManifest.create(
                dataset_fingerprint=dataset.fingerprint,
                config_hash=compute_config_hash(config),
                rules_executed=["completeness", "uniqueness"],
                final_score=87.3,
            )
        """
        return cls(
            run_id=str(uuid.uuid4()),
            timestamp=datetime.now(tz=timezone.utc).isoformat(),
            dataset_fingerprint=dataset_fingerprint,
            config_hash=config_hash,
            sdk_version=_sdk_version(),
            python_version=sys.version,
            environment=_build_environment(),
            rules_executed=list(rules_executed),
            drift_checks_executed=list(drift_checks_executed or []),
            final_score=final_score,
        )

    # ------------------------------------------------------------------
    # Serialisation
    # ------------------------------------------------------------------

    def to_dict(self) -> Dict[str, object]:
        """
        Return a plain dictionary representation suitable for JSON serialisation.

        Returns:
            Dict with all manifest fields as primitive types.
        """
        return {
            "run_id": self.run_id,
            "timestamp": self.timestamp,
            "dataset_fingerprint": self.dataset_fingerprint,
            "config_hash": self.config_hash,
            "sdk_version": self.sdk_version,
            "python_version": self.python_version,
            "environment": dict(self.environment),
            "rules_executed": list(self.rules_executed),
            "drift_checks_executed": list(self.drift_checks_executed),
            "final_score": self.final_score,
        }

    def to_json(self, indent: int = 2) -> str:
        """
        Serialise the manifest to a JSON string.

        Args:
            indent: JSON indentation level (default: 2).

        Returns:
            A formatted JSON string.
        """
        return json.dumps(self.to_dict(), indent=indent, default=str)
